apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-lock-config
data:
  PORT: "8080"
  DB_HOST: "${DB_HOST}" # GitHub Secretsから注入
  DB_PORT: "${DB_PORT}" # GitHub Secretsから注入
  DB_NAME: "${DB_NAME}" # GitHub Secretsから注入
